// <auto-generated>
// Generated by tools/datasources/run.py gen-cs from tools/guo/formats.py.
// Do not edit: change formats.py and regenerate. CI checks it is current.
// </auto-generated>
namespace GUO.Host;

/// <summary>The required client data entries (ADR-0021 validity rule).</summary>
internal static class DataRequirements
{
    internal sealed record Entry(string Key, string[] Mul, string[] Uop, string[] Index);

    internal static readonly Entry[] Required =
    {
        new("tiledata", new[] { "tiledata.mul" }, System.Array.Empty<string>(), System.Array.Empty<string>()),
        new("hues", new[] { "hues.mul" }, System.Array.Empty<string>(), System.Array.Empty<string>()),
        new("art", new[] { "art.mul" }, new[] { "artLegacyMUL.uop" }, new[] { "artidx.mul" }),
        new("texmaps", new[] { "texmaps.mul" }, System.Array.Empty<string>(), new[] { "texidx.mul" }),
        new("gumpart", new[] { "gumpart.mul" }, new[] { "gumpartLegacyMUL.uop" }, new[] { "gumpidx.mul" }),
        new("multi", new[] { "multi.mul" }, new[] { "MultiCollection.uop" }, new[] { "multi.idx" }),
        new("anim", new[] { "anim.mul" }, new[] { "AnimationFrame1.uop" }, new[] { "anim.idx" }),
        new("fonts", new[] { "fonts.mul" }, System.Array.Empty<string>(), System.Array.Empty<string>()),
        new("cliloc", new[] { "cliloc.enu" }, System.Array.Empty<string>(), System.Array.Empty<string>()),
        new("skills", new[] { "skills.mul" }, System.Array.Empty<string>(), new[] { "skills.idx" }),
        new("map0", new[] { "map0.mul" }, new[] { "map0LegacyMUL.uop", "map0xLegacyMUL.uop" }, System.Array.Empty<string>()),
        new("statics0", new[] { "statics0.mul", "statics0x.mul" }, System.Array.Empty<string>(), new[] { "staidx0.mul", "staidx0x.mul" }),
    };
}
