<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><DefineConstants>TOOLS</DefineConstants><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../../../godot/GUO/addons/guo_editor/ServerProfiles.cs" Link="ServerProfiles.cs" /><Compile Include="../../../godot/GUO/src/Workspace/*.cs" Link="Workspace/%(Filename)%(Extension)" /></ItemGroup></Project>
