"""The dev shard's generated passwords: one local file per user, never committed.

The local ModernUO shard has an owner account and a few game master accounts
(UO_SHARD_OWNER, UO_SHARD_GM_ACCOUNTS). Their passwords are not defaults in
config.bat any more: the first `tools/modernuo/configure.py` makes random ones
and writes them here, in the per-user workspace (ADR-0032):

    <UO_WORKSPACE_DIR>/shard/secrets.bat

It is a .bat of guarded `set` lines, the same narrow form as config.bat, so
common.bat `call`s it after config.bat and tools/guo/config.py parses it with
the same reader. An environment variable or a line in config.local.bat still
wins over it. Nothing prints a password in full; tools that need one read it
from the resolved configuration.
"""

from __future__ import annotations

import os
import secrets
import string
from pathlib import Path

OWNER_KEY = "UO_SHARD_OWNER_PASSWORD"
GM_KEY = "UO_SHARD_GM_PASSWORD"
KEYS = (OWNER_KEY, GM_KEY)

# Letters and digits only: a password the login gump, a .bat line, a shell
# export and a JSON string all carry without quoting. ModernUO takes up to 30.
_ALPHABET = string.ascii_letters + string.digits
LENGTH = 20

HEADER = """@echo off
REM Generated by tools\\modernuo\\configure.py: the local dev shard's passwords.
REM Per user, outside the repository; never commit or share this file.
REM Delete it and run launchers\\shard\\run.bat again for new ones (the shard
REM resets the owner and game master passwords to these at every boot).
"""


def path_for(workspace: Path) -> Path:
    return Path(workspace) / "shard" / "secrets.bat"


def generate() -> str:
    return "".join(secrets.choice(_ALPHABET) for _ in range(LENGTH))


def read(path: Path) -> dict[str, str]:
    """The values in a secrets file, or {} when there is none."""
    from .config import _SET_RE

    if not Path(path).is_file():
        return {}
    # The file's own values, whatever the environment holds: its guards are
    # for common.bat, not for this reader.
    values = {}
    for line in Path(path).read_text(encoding="utf-8-sig", errors="replace").splitlines():
        match = _SET_RE.match(line)
        if match and match.group("key").upper() in KEYS and match.group("val"):
            values[match.group("key").upper()] = match.group("val")
    return values


def ensure(workspace: Path) -> tuple[Path, list[str]]:
    """Make sure the file holds a password for every key; return it and the keys it added.

    Existing values are kept, so every worktree and every run of one user
    shares the same passwords until the file is deleted.
    """
    path = path_for(workspace)
    values = read(path)
    added = [key for key in KEYS if not values.get(key)]
    if not added:
        return path, []
    for key in added:
        values[key] = generate()
    path.parent.mkdir(parents=True, exist_ok=True)
    body = HEADER + "".join(f'if not defined {key} set "{key}={values[key]}"\n' for key in KEYS)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(body.replace("\n", "\r\n"), encoding="utf-8", newline="")
    try:
        os.chmod(tmp, 0o600)
    except OSError:
        pass
    os.replace(tmp, path)
    return path, added


def hint(value: str) -> str:
    """Enough of a password to tell two apart in a log, never the whole of it."""
    return f"{value[:2]}...({len(value)} chars)" if value else "(none)"
