"""The dev shard's generated passwords: one local file per user, never committed.

The local ModernUO shard has an owner account and a few game master accounts
(UO_SHARD_OWNER, UO_SHARD_GM_ACCOUNTS). Their passwords are not defaults in
config.bat any more: the first `tools/modernuo/configure.py` makes random ones
and writes them here, in the per-user workspace (ADR-0032):

    <UO_WORKSPACE_DIR>/shard/secrets.bat

It is a .bat of guarded `set` lines, the same narrow form as config.bat, so
common.bat `call`s it after config.bat and tools/guo/config.py parses it with
the same reader. An environment variable or a line in config.local.bat still
wins over it. Nothing prints a password in full; tools that need one read it
from the resolved configuration.

The same file holds the editor bridge's admin token (UO_BRIDGE_ADMIN_TOKEN,
ADR-0035): the secret an editor sends in its bridge `hello` before any admin
op. tools/editor_shard hands it to the private shard it starts; nothing logs
or prints it, and it travels only to the loopback bridge.

The Admin tab's Settings form (AD4) adds keys of its own for server settings
that are secrets (UO_SHARD_EMAIL_PASSWORD, UO_SHARD_DISCORD_WEBHOOK, ...);
ensure() keeps every line it does not own.
"""

from __future__ import annotations

import os
import secrets
import string
from pathlib import Path

OWNER_KEY = "UO_SHARD_OWNER_PASSWORD"
GM_KEY = "UO_SHARD_GM_PASSWORD"
ADMIN_TOKEN_KEY = "UO_BRIDGE_ADMIN_TOKEN"
KEYS = (OWNER_KEY, GM_KEY, ADMIN_TOKEN_KEY)

# Letters and digits only: a password the login gump, a .bat line, a shell
# export and a JSON string all carry without quoting. ModernUO takes up to 30,
# but the login gump's password box holds 16 (LoginGump.cs, as upstream): a
# longer one is cut short when it is typed, and that login fails (AD5).
_ALPHABET = string.ascii_letters + string.digits
LENGTH = 16
# The owner and game master passwords: people type them into the login gump.
PASSWORD_KEYS = (OWNER_KEY, GM_KEY)
# The admin token is typed by nobody, so it can be longer: 32 of 62 symbols.
TOKEN_LENGTH = 32

HEADER = """@echo off
REM Generated by tools\\modernuo\\configure.py: the local dev shard's passwords
REM and the editor bridge's admin token (ADR-0035).
REM Per user, outside the repository; never commit or share this file.
REM Delete it and run launchers\\shard\\run.bat again for new ones (the shard
REM resets the owner and game master passwords to these at every boot).
"""


def path_for(workspace: Path) -> Path:
    return Path(workspace) / "shard" / "secrets.bat"


def generate(length: int = LENGTH) -> str:
    return "".join(secrets.choice(_ALPHABET) for _ in range(length))


def read(path: Path) -> dict[str, str]:
    """The values in a secrets file, or {} when there is none."""
    from .config import _SET_RE

    if not Path(path).is_file():
        return {}
    # The file's own values, whatever the environment holds: its guards are
    # for common.bat, not for this reader.
    values = {}
    for line in Path(path).read_text(encoding="utf-8-sig", errors="replace").splitlines():
        match = _SET_RE.match(line)
        if match and match.group("key").upper() in KEYS and match.group("val"):
            values[match.group("key").upper()] = match.group("val")
    return values


def _other_lines(path: Path) -> list[str]:
    """The file's `set` lines for keys other than KEYS, as written."""
    from .config import _SET_RE

    if not Path(path).is_file():
        return []
    lines = Path(path).read_text(encoding="utf-8-sig", errors="replace").splitlines()
    return [line for line in lines if (m := _SET_RE.match(line)) and m.group("key").upper() not in KEYS]


def ensure(workspace: Path) -> tuple[Path, list[str]]:
    """Make sure the file holds a password for every key; return it and the keys it added or replaced.

    Existing values are kept, so every worktree and every run of one user
    shares the same passwords until the file is deleted. The one exception is
    an owner or game master password longer than the login gump's box (one
    generated before AD5 has 20 characters): it is replaced by a new one that
    fits. The shard sets its staff accounts to the new password at its next
    start (patch 0001), so nothing else has to change.
    """
    path = path_for(workspace)
    values = read(path)
    added = [key for key in KEYS if not values.get(key)
             or key in PASSWORD_KEYS and len(values[key]) > LENGTH]
    if not added:
        return path, []
    for key in added:
        values[key] = generate(TOKEN_LENGTH if key == ADMIN_TOKEN_KEY else LENGTH)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = HEADER + "".join(f'if not defined {key} set "{key}={values[key]}"\n' for key in KEYS)
    # Keys this module does not own stay as they were: the Admin tab's Settings form keeps a server
    # setting that is a secret here (a mail password, a webhook; AD4).
    body += "".join(f"{line}\n" for line in _other_lines(path))
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(body.replace("\n", "\r\n"), encoding="utf-8", newline="")
    try:
        os.chmod(tmp, 0o600)
    except OSError:
        pass
    os.replace(tmp, path)
    return path, added


def hint(value: str) -> str:
    """Enough of a password to tell two apart in a log, never the whole of it."""
    return f"{value[:2]}...({len(value)} chars)" if value else "(none)"
