<Project>
  <PropertyGroup><BaseIntermediateOutputPath>../../build/animation_checks/obj/</BaseIntermediateOutputPath></PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>
    <DefineConstants>TOOLS</DefineConstants><EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>../../build/animation_checks/bin/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../godot/GUO/addons/guo_editor/Animation/AnimationDocument.cs" Link="AnimationDocument.cs" />
    <Compile Include="VdChecks.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
