#if TOOLS
namespace GUO.Editor;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using Godot;

/// <summary>
/// StaticStudio: pick any static in the world, generate new artwork for it
/// with ComfyUI, and save the result as a theme entry (image variant and/or
/// gaussian splat), then paint zones or multis with the theme. JarJarGM's flow
/// (target, extract, generate, apply, toggle back) on GUO's own machinery:
/// the Art dock's providers, the asset overlay, ThemeManager and SplatObjects.
/// The 3D itself is generated by tools/comfy; this dock stages and places it.
/// </summary>
[Tool]
public partial class StaticStudioDock : EditorDock
{
    private EditorData _data;
    private Func<Inspection> _source = () => null;
    private Func<GUO.Game.World> _world;
    private CancellationTokenSource _cts = new();
    private bool _ready;

    private Label _target, _status;
    private LineEdit _prompt, _themeName, _zone, _placeX, _placeY, _placeZ;
    private OptionButton _workflowPick, _splatPick;
    private ItemList _gallery;
    private Button _queue, _saveVariant;
    private readonly List<Image> _images = new();
    private ImageResult _lastResult;
    private string _lastWorkflow = "";
    private long _lastSeed = -1;

    private AssetKind? _targetKind;
    private int _targetId = -1;

    public StaticStudioDock()
    {
        Name = "UOStaticStudio";
        Title = "StaticStudio";
        LayoutKey = "guo_staticstudio";
        DefaultSlot = DockSlot.Bottom;
        AvailableLayouts = DockLayout.Horizontal | DockLayout.Vertical | DockLayout.Floating;
        IconName = "Image";
    }

    internal void Attach(EditorData data, Func<Inspection> source, Func<GUO.Game.World> world)
    {
        _data = data;
        _source = source ?? (() => null);
        _world = world;
    }

    public string Status => _status?.Text ?? "";

    public int GalleryCount => _images.Count;

    public override void _Ready()
    {
        if (_ready)
        {
            return;
        }

        _ready = true;
        var root = new VBoxContainer();
        root.SetAnchorsPreset(LayoutPreset.FullRect);
        AddChild(root);

        var pick = new HBoxContainer();
        root.AddChild(pick);
        var pickBtn = new Button { Text = "Use inspected static" };
        pickBtn.Pressed += BindTarget;
        pick.AddChild(pickBtn);
        _target = new Label { Text = "(nothing bound: pick art in the UO Inspector)", SizeFlagsHorizontal = SizeFlags.ExpandFill };
        pick.AddChild(_target);

        var wf = new HBoxContainer();
        root.AddChild(wf);
        wf.AddChild(new Label { Text = "Workflow" });
        _workflowPick = new OptionButton { SizeFlagsHorizontal = SizeFlags.ExpandFill };
        wf.AddChild(_workflowPick);
        var refresh = new Button { Text = "Refresh" };
        refresh.Pressed += RefreshWorkflows;
        wf.AddChild(refresh);

        _prompt = new LineEdit { PlaceholderText = "prompt (img2img over the bound static)", SizeFlagsHorizontal = SizeFlags.ExpandFill };
        root.AddChild(_prompt);

        var go = new HBoxContainer();
        root.AddChild(go);
        _queue = new Button { Text = "Generate image" };
        _queue.Pressed += () => _ = QueueFromUi();
        go.AddChild(_queue);

        _gallery = new ItemList
        {
            SizeFlagsVertical = SizeFlags.ExpandFill,
            CustomMinimumSize = new Vector2(0, 96),
            IconMode = ItemList.IconModeEnum.Top,
            FixedIconSize = new Vector2I(96, 96),
            MaxColumns = 0,
            TextureFilter = TextureFilterEnum.Nearest,
        };
        root.AddChild(_gallery);

        var theme = new HBoxContainer();
        root.AddChild(theme);
        theme.AddChild(new Label { Text = "Theme" });
        _themeName = new LineEdit { Text = "spooky", SizeFlagsHorizontal = SizeFlags.ExpandFill };
        theme.AddChild(_themeName);
        _saveVariant = new Button { Text = "Save gallery image as theme variant" };
        _saveVariant.Pressed += () => Report(SaveVariant());
        theme.AddChild(_saveVariant);

        var splat = new HBoxContainer();
        root.AddChild(splat);
        splat.AddChild(new Label { Text = "Splat" });
        _splatPick = new OptionButton { SizeFlagsHorizontal = SizeFlags.ExpandFill };
        splat.AddChild(_splatPick);
        var splatRefresh = new Button { Text = "Refresh" };
        splatRefresh.Pressed += RefreshSplats;
        splat.AddChild(splatRefresh);

        var at = new HBoxContainer();
        root.AddChild(at);
        at.AddChild(new Label { Text = "At x,y,z" });
        _placeX = new LineEdit { CustomMinimumSize = new Vector2(70, 0) };
        at.AddChild(_placeX);
        _placeY = new LineEdit { CustomMinimumSize = new Vector2(70, 0) };
        at.AddChild(_placeY);
        _placeZ = new LineEdit { Text = "0", CustomMinimumSize = new Vector2(50, 0) };
        at.AddChild(_placeZ);
        var center = new Button { Text = "View centre" };
        center.Pressed += FillCentre;
        at.AddChild(center);
        var place = new Button { Text = "Place splat" };
        place.Pressed += () => Report(PlaceSplat());
        at.AddChild(place);

        var zone = new HBoxContainer();
        root.AddChild(zone);
        zone.AddChild(new Label { Text = "Zone facet,x1,y1,x2,y2" });
        _zone = new LineEdit { SizeFlagsHorizontal = SizeFlags.ExpandFill };
        zone.AddChild(_zone);
        var apply = new Button { Text = "Apply theme to zone" };
        apply.Pressed += () => Report(ApplyZone());
        zone.AddChild(apply);
        var clear = new Button { Text = "Clear" };
        clear.Pressed += () => Report(ClearThemes());
        zone.AddChild(clear);

        _status = new Label { AutowrapMode = TextServer.AutowrapMode.WordSmart };
        root.AddChild(_status);
        RefreshWorkflows();
        RefreshSplats();
    }

    private void Report(string text)
    {
        if (_status != null)
        {
            _status.Text = text ?? "";
        }

        if (text != null)
        {
            GD.Print($"[GUO editor] staticstudio: {text}");
        }
    }

    // --- target -----------------------------------------------------------------

    private void BindTarget()
    {
        Inspection ins = _source();
        if (ins?.ArtKind == null)
        {
            Report("nothing to bind: pick art or a gump in the UO Inspector");
            return;
        }

        _targetKind = ins.ArtKind;
        _targetId = ins.ArtId;
        _target.Text = $"{ArtSidecar.KindName(ins.ArtKind.Value)} 0x{ins.ArtId:X4}";
        Report($"bound {_target.Text}");
    }

    /// <summary>Binds a target without the UI (the smoke check).</summary>
    public void BindTarget(AssetKind kind, int id, Image image)
    {
        _targetKind = kind;
        _targetId = id;
        _boundImage = image;
        if (_target != null)
        {
            _target.Text = $"{ArtSidecar.KindName(kind)} 0x{id:X4}";
        }
    }

    /// <summary>Runs an image request on a worker and files the gallery (the smoke check).</summary>
    public async Task<ImageResult> RunImageAsync(IImageProvider provider, ImageRequest req)
    {
        ImageResult r = await Task.Run(() => provider.RunAsync(req, null, _cts.Token));
        Finish(r);
        return r;
    }

    private Image _boundImage;

    // --- image jobs (the Art dock's providers) -----------------------------------

    private void RefreshWorkflows()
    {
        _workflowPick.Clear();
        foreach (string f in ComfyUiProvider.Workflows(ArtDock.WorkflowFolder))
        {
            _workflowPick.AddItem(Path.GetFileName(f));
            _workflowPick.SetItemMetadata(_workflowPick.ItemCount - 1, f);
        }

        if (_workflowPick.ItemCount == 0)
        {
            _workflowPick.AddItem("(no workflows: put API-format .json files in the workflow folder)");
            _workflowPick.Disabled = true;
        }
        else
        {
            _workflowPick.Disabled = false;
        }
    }

    private async Task QueueFromUi()
    {
        string url = EditorData.Setting("UO_COMFY_URL", "http://127.0.0.1:8188");
        var provider = new ComfyUiProvider(url);
        string wf = _workflowPick.ItemCount > 0 && !_workflowPick.Disabled
            ? (string)_workflowPick.GetItemMetadata(_workflowPick.Selected) : "";
        ImageRequest req = BuildRequest(_prompt.Text, wf);
        if (req == null)
        {
            return;
        }

        Report($"queued on {provider.Name}...");
        ImageResult r = await Task.Run(() => provider.RunAsync(req, null, _cts.Token));
        Finish(r);
        Report(r.Error ?? $"{r.Pngs.Count} image(s) ready; pick one and save it as a theme variant");
        provider.Dispose();
    }

    /// <summary>The request for a prompt, a workflow file and the bound static as input.</summary>
    public ImageRequest BuildRequest(string prompt, string workflowPath)
    {
        if (_targetKind == null)
        {
            Report("no target: bind a static first");
            return null;
        }

        Image img = _boundImage ?? _source()?.Image;
        if (img == null)
        {
            Report("no pixels for the bound static: show it in the UO Inspector");
            return null;
        }

        return new ImageRequest
        {
            Prompt = prompt ?? "",
            WorkflowPath = workflowPath ?? "",
            InputPng = img.SavePngToBuffer(),
            InputName = $"client:{ArtSidecar.KindName(_targetKind.Value)}:0x{_targetId:X4}",
            InputIsClientArt = true,
            Width = img.GetWidth(),
            Height = img.GetHeight(),
        };
    }

    private void Finish(ImageResult r)
    {
        _lastResult = r;
        _lastWorkflow = r.Workflow;
        _lastSeed = r.Seed;
        _images.Clear();
        _gallery?.Clear();
        foreach (byte[] png in r.Pngs)
        {
            var img = new Image();
            if (img.LoadPngFromBuffer(png) == Error.Ok)
            {
                _images.Add(img);
                _gallery?.AddItem($"{img.GetWidth()}x{img.GetHeight()}", ImageTexture.CreateFromImage(img));
            }
        }

        if (_gallery != null && _images.Count > 0)
        {
            _gallery.Select(0);
        }
    }

    // --- theme variants ----------------------------------------------------------

    /// <summary>Where this world project's themes live (created on first save).</summary>
    public static string ThemeDir(EditorData data)
    {
        string root = null;
        try
        {
            root = data?.Assets?.Root;
        }
        catch (Exception)
        {
        }

        return Path.Combine(root ?? EditorData.RepoRoot, "themes");
    }

    /// <summary>
    /// Saves the selected gallery image as a theme variant: overlay PNG at a
    /// free static id plus a theme entry mapping the bound graphic at it.
    /// Returns a status line (the reason when it did not save).
    /// </summary>
    public string SaveVariant(int index = -1, string theme = null)
    {
        if (_data?.Assets == null)
        {
            return "no world project is open";
        }

        if (index < 0)
        {
            int[] sel = _gallery?.GetSelectedItems() ?? System.Array.Empty<int>();
            index = sel.Length > 0 ? sel[0] : 0;
        }

        if (index >= _images.Count || _lastResult == null)
        {
            return "nothing in the gallery: generate an image first";
        }

        if (_targetKind == null || _targetKind == AssetKind.Hue)
        {
            return "no static bound: bind a land tile, static or gump first";
        }

        theme = (theme ?? _themeName?.Text ?? "").Trim();
        if (theme.Length == 0)
        {
            return "name the theme first";
        }

        int variant = NextVariantId(theme);
        if (variant < 0)
        {
            return "no free variant id left in 0xF000-0xFEFF";
        }
        var prov = new ArtProvenance
        {
            Tool = "comfyui",
            Workflow = _lastWorkflow,
            Kind = "",
            Seed = _lastSeed >= 0 ? _lastSeed : null,
            DerivedFromClientArt = true,
        };
        prov.Inputs.Add($"client:{ArtSidecar.KindName(_targetKind.Value)}:0x{_targetId:X4}");

        var notes = new List<string>();
        string why = ArtExchange.ImportImage(_data, _targetKind.Value, variant, _images[index], prov, notes);
        if (why != null)
        {
            return $"refused: {why}";
        }

        AppendThemeEntry(theme, (ushort)_targetId, (ushort)variant);
        return $"saved {theme}: 0x{_targetId:X4} -> variant 0x{variant:X4} ({string.Join("; ", notes)})";
    }

    /// <summary>The next free variant id for a theme: 0xF000 up, skipping what the theme already uses.</summary>
    public int NextVariantId(string theme)
    {
        var used = new HashSet<int>();
        foreach (var e in ReadThemeEntries(theme))
        {
            used.Add(e.Variant);
        }

        for (int id = 0xF000; id < 0xFF00; id++)
        {
            if (!used.Contains(id) && !(_data?.Assets?.Has(AssetKind.Static, id) ?? false))
            {
                return id;
            }
        }

        return -1;
    }

    private List<(ushort Match, ushort Variant)> ReadThemeEntries(string theme)
    {
        var out_ = new List<(ushort, ushort)>();
        string path = Path.Combine(ThemeDir(_data), theme + ".theme.json");
        if (!File.Exists(path))
        {
            return out_;
        }

        try
        {
            JsonNode root = JsonNode.Parse(File.ReadAllText(path));
            if (root?["entries"] is JsonArray entries)
            {
                foreach (JsonNode e in entries)
                {
                    if (e?["match"] is JsonArray match && e["variant"] is JsonNode v)
                    {
                        foreach (JsonNode m in match)
                        {
                            out_.Add(((ushort)(int)m, (ushort)(int)v));
                        }
                    }
                }
            }
        }
        catch (Exception)
        {
        }

        return out_;
    }

    private void AppendThemeEntry(string theme, ushort match, ushort variant)
    {
        string dir = ThemeDir(_data);
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, theme + ".theme.json");
        JsonObject root;
        JsonArray entries;
        try
        {
            root = File.Exists(path) && JsonNode.Parse(File.ReadAllText(path)) is JsonObject o ? o : new JsonObject();
            entries = root["entries"] as JsonArray ?? new JsonArray();
        }
        catch (Exception)
        {
            root = new JsonObject();
            entries = new JsonArray();
        }

        root["format"] = 1;
        root["name"] = theme;
        entries.Add(new JsonObject
        {
            ["match"] = new JsonArray(match),
            ["variant"] = variant,
        });
        root["entries"] = entries;
        if (root["multis"] == null)
        {
            root["multis"] = new JsonArray();
        }

        File.WriteAllText(path, root.ToJsonString(new System.Text.Json.JsonSerializerOptions { WriteIndented = true }));
    }

    // --- splats ------------------------------------------------------------------

    private void RefreshSplats()
    {
        _splatPick.Clear();
        foreach (string name in StagedSplatNames())
        {
            _splatPick.AddItem(name);
        }

        if (_splatPick.ItemCount == 0)
        {
            _splatPick.AddItem("(no staged splats: run tools/comfy/stage.py)");
            _splatPick.Disabled = true;
        }
        else
        {
            _splatPick.Disabled = false;
        }
    }

    /// <summary>Staged splat names from the manifest (or empty).</summary>
    public static List<string> StagedSplatNames()
    {
        var names = new List<string>();
        try
        {
            string stage = System.Environment.GetEnvironmentVariable("GUO_SPLAT_STAGE");
            if (string.IsNullOrWhiteSpace(stage))
            {
                stage = Path.Combine(EditorData.RepoRoot, "build", "staged", "guo-comfy-gen");
            }

            string manifest = Path.Combine(stage, "splats.json");
            if (File.Exists(manifest) && JsonNode.Parse(File.ReadAllText(manifest))?["splats"] is JsonObject splats)
            {
                foreach (var kv in splats)
                {
                    names.Add(kv.Key);
                }
            }
        }
        catch (Exception)
        {
        }

        return names;
    }

    /// <summary>Fills the placement fields from the world view centre (the player).</summary>
    public void FillCentre()
    {
        GUO.Game.World world = _world?.Invoke();
        if (world?.Player == null)
        {
            Report("no world open");
            return;
        }

        _placeX.Text = world.Player.X.ToString();
        _placeY.Text = world.Player.Y.ToString();
        _placeZ.Text = world.Player.Z.ToString();
    }

    /// <summary>
    /// Records a placement for the picked splat at the typed tile in
    /// the staged manifest (created if missing). The live scene and the editor
    /// world both draw it from there.
    /// </summary>
    public string PlaceSplat()
    {
        if (!int.TryParse(_placeX?.Text, out int x) || !int.TryParse(_placeY?.Text, out int y))
        {
            return "type the tile x,y first (or View centre)";
        }

        int z = int.TryParse(_placeZ?.Text, out int zz) ? zz : 0;
        string name = !_splatPick.Disabled ? _splatPick.GetItemText(_splatPick.Selected) : "";
        return PlaceSplatAt(name, x, y, z);
    }

    /// <summary>Placement core without the UI (the smoke check).</summary>
    public string PlaceSplatAt(string name, int x, int y, int z)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "no staged splat to place";
        }

        try
        {
            string stage = System.Environment.GetEnvironmentVariable("GUO_SPLAT_STAGE");
            if (string.IsNullOrWhiteSpace(stage))
            {
                stage = Path.Combine(EditorData.RepoRoot, "build", "staged", "guo-comfy-gen");
            }

            Directory.CreateDirectory(stage);
            string manifest = Path.Combine(stage, "splats.json");
            JsonObject root = File.Exists(manifest) && JsonNode.Parse(File.ReadAllText(manifest)) is JsonObject o
                ? o : new JsonObject { ["format"] = "guo/comfy-splats@1" };
            JsonObject splats = root["splats"] as JsonObject ?? new JsonObject();
            JsonObject entry = splats[name] as JsonObject;
            if (entry == null)
            {
                return $"staged manifest has no splat named '{name}'";
            }

            entry["placement"] = new JsonObject { ["facet"] = 0, ["x"] = x, ["y"] = y, ["z"] = z };
            splats[name] = entry;
            root["splats"] = splats;
            File.WriteAllText(manifest, root.ToJsonString(new System.Text.Json.JsonSerializerOptions { WriteIndented = true }));
            return $"placed {name} at {x},{y},{z} (re-stage or re-open the world to see it)";
        }
        catch (Exception ex)
        {
            return $"could not write the staged manifest: {ex.Message}";
        }
    }

    // --- zones -------------------------------------------------------------------

    /// <summary>Activates the named theme over a parsed zone and repaints the world.</summary>
    public string ApplyZone()
    {
        return ApplyZone((_themeName?.Text ?? "").Trim(), _zone?.Text ?? "");
    }

    /// <summary>Zone apply without the UI (the smoke check).</summary>
    public string ApplyZone(string theme, string zoneText)
    {
        if (theme.Length == 0)
        {
            return "name the theme first";
        }

        string[] parts = zoneText.Split(',');
        if (parts.Length < 5
            || !int.TryParse(parts[0], out int f) || !int.TryParse(parts[1], out int x1)
            || !int.TryParse(parts[2], out int y1) || !int.TryParse(parts[3], out int x2)
            || !int.TryParse(parts[4], out int y2))
        {
            return "zone reads 'facet,x1,y1,x2,y2', e.g. 0,1424,1688,1444,1711";
        }

        string path = Path.Combine(ThemeDir(_data), theme + ".theme.json");
        if (!File.Exists(path))
        {
            return $"no theme file {path}: save a variant first";
        }

        GUO.Game.Managers.Theme themeData;
        try
        {
            themeData = GUO.Game.Managers.Theme.Load(path);
        }
        catch (Exception ex)
        {
            return $"could not read {path}: {ex.Message}";
        }

        GUO.Game.Managers.ThemeManager.Activate(themeData,
            new List<GUO.Game.Managers.ThemeZone> { new() { Facet = f, X1 = x1, Y1 = y1, X2 = x2, Y2 = y2 } });
        GUO.Game.World world = _world?.Invoke();
        if (world == null)
        {
            return $"theme {theme} armed (no world open to repaint)";
        }

        GUO.Game.Managers.ThemeManager.Reapply(world);
        return $"theme {theme} paints facet {f} {x1},{y1}-{x2},{y2}";
    }

    /// <summary>Clears every theme and repaints originals.</summary>
    public string ClearThemes()
    {
        GUO.Game.Managers.ThemeManager.Clear();
        GUO.Game.World world = _world?.Invoke();
        if (world != null)
        {
            GUO.Game.Managers.ThemeManager.Reapply(world);
        }

        return "themes cleared: originals restored";
    }

    /// <summary>Cancels running work; called before a reload or when the dock closes.</summary>
    public void Shutdown()
    {
        _cts.Cancel();
        _cts = new CancellationTokenSource();
    }
}
#endif
